# Generated by Django 3.1.7 on 2022-09-02 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0009_auto_20220830_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTaskAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.unit', validators=[student_tasks.models.validate_is_task])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
