# Generated by Django 3.1.7 on 2022-10-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220926_1224'),
        ('student_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttaskanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='studenttaskanswer',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
