# Generated by Django 3.1.7 on 2022-11-08 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20221107_2307'),
        ('student_tasks', '0002_auto_20221007_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttaskanswer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_done', to='accounts.profile'),
        ),
    ]
