# Generated by Django 3.1.7 on 2022-08-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_bonuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('for_gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6)),
                ('time_cost', models.IntegerField()),
                ('money_cost', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('bonuses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.bonuses')),
                ('laboratory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('markup', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('content', models.JSONField(default=dict)),
                ('lesson_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lessonblock')),
                ('next', models.ManyToManyField(blank=True, related_name='_unit_next_+', to='lessons.Unit')),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.unittype')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course')),
            ],
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.unit'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='lessons.unit'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.quest'),
        ),
        migrations.CreateModel(
            name='Branching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_type', models.CharField(choices=[('conditional', 'Условный бранчинг'), ('selective', 'Выборочный бранчинг')], max_length=32)),
                ('type', models.IntegerField()),
                ('content', models.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course')),
            ],
        ),
    ]
