# Generated by Django 3.1.7 on 2022-08-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
                ('url', models.CharField(max_length=1027)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckboxesBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('if_correct', models.CharField(max_length=1023)),
                ('if_incorrect', models.CharField(max_length=1023)),
                ('variants', models.JSONField()),
                ('correct', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComparisonBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('if_correct', models.CharField(max_length=1023)),
                ('if_incorrect', models.CharField(max_length=1023)),
                ('lists', models.JSONField()),
                ('correct', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('entry', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('locale', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DocBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
                ('npc', models.IntegerField()),
                ('subject', models.TextField()),
                ('f_from', models.TextField()),
                ('to', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('images', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageAnchorsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('if_correct', models.CharField(max_length=1023)),
                ('if_incorrect', models.CharField(max_length=1023)),
                ('anchors', models.JSONField()),
                ('options', models.JSONField()),
                ('img_url', models.CharField(max_length=1027)),
                ('correct', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('url', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportantBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('if_correct', models.CharField(max_length=1023)),
                ('if_incorrect', models.CharField(max_length=1023)),
                ('correct', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField(blank=True, default=None, null=True)),
                ('local_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('for_gender', models.CharField(choices=[('any', 'Любой'), ('male', 'Мужской'), ('female', 'Женский')], default='any', max_length=6)),
                ('time_cost', models.IntegerField()),
                ('money_cost', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('bonuses', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.JSONField(default=dict)),
                ('markup', models.JSONField(default={'en': [], 'ru': []})),
                ('entry', models.CharField(blank=True, default=None, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('if_correct', models.CharField(max_length=1023)),
                ('if_incorrect', models.CharField(max_length=1023)),
                ('tolerance', models.IntegerField()),
                ('correct', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadiosBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('if_correct', models.CharField(max_length=1023)),
                ('if_incorrect', models.CharField(max_length=1023)),
                ('variants', models.JSONField()),
                ('correct', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadiosTableBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('if_correct', models.CharField(max_length=1023)),
                ('if_incorrect', models.CharField(max_length=1023)),
                ('columns', models.JSONField()),
                ('rows', models.JSONField()),
                ('is_radio', models.BooleanField()),
                ('correct', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplicaBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
                ('emotion', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('if_correct', models.CharField(max_length=1023)),
                ('if_incorrect', models.CharField(max_length=1023)),
                ('body', models.TextField()),
                ('selects', models.JSONField()),
                ('correct', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SortBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('if_correct', models.CharField(max_length=1023)),
                ('if_incorrect', models.CharField(max_length=1023)),
                ('options', models.JSONField()),
                ('correct', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('url', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TheoryBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('url', models.CharField(max_length=127)),
                ('location', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplicaNPCBlock',
            fields=[
                ('replicablock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lessons.replicablock')),
                ('npc', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('lessons.replicablock',),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField(blank=True, default=None, null=True)),
                ('local_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('type', models.IntegerField()),
                ('content', models.JSONField()),
                ('next', models.JSONField()),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson')),
                ('lesson_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='lessons.lessonblock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField(blank=True, default=None, null=True)),
                ('local_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('entry', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('next', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='lessons.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lessons.lessonblock'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.laboratory'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lessons.quest'),
        ),
        migrations.CreateModel(
            name='Branching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField(blank=True, default=None, null=True)),
                ('local_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('type', models.IntegerField()),
                ('content', models.JSONField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branchings', to='lessons.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
