# Generated by Django 3.1.7 on 2022-08-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='locale',
            field=models.JSONField(default=dict),
        ),
    ]
