# Generated by Django 3.1.7 on 2022-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_branching_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_bonuses',
            field=models.BooleanField(default=False),
        ),
    ]
