# Generated by Django 3.1.7 on 2022-08-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_has_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next',
            field=models.CharField(default='', max_length=255),
        ),
    ]
