# Generated by Django 3.1.7 on 2022-08-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='branching',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='branching',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
