# Generated by Django 3.1.7 on 2022-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20220817_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branching',
            name='local_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='local_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='quest',
            name='local_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='local_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
