# Generated by Django 3.1.7 on 2022-08-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20220817_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='next',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
