# Generated by Django 3.1.7 on 2022-08-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_buttonblock_downloadingblock_messengerendblock_messengerstartblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailblock',
            old_name='f_from',
            new_name='sender',
        ),
    ]
