# Generated by Django 3.1.7 on 2022-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20220907_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=31)),
                ('image', models.ImageField(upload_to='locations')),
                ('image_disabled', models.ImageField(upload_to='locations')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=7, unique=True)),
                ('ru_name', models.CharField(max_length=31)),
                ('en_name', models.CharField(max_length=31)),
                ('gender', models.CharField(choices=[('any', 'Любой'), ('male', 'Мужской'), ('female', 'Женский')], max_length=6)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('usual_image', models.ImageField(upload_to='npc_emotions')),
                ('angry_image', models.ImageField(upload_to='npc_emotions')),
                ('fair_image', models.ImageField(upload_to='npc_emotions')),
                ('sad_image', models.ImageField(upload_to='npc_emotions')),
            ],
        ),
    ]
