# Generated by Django 3.1.7 on 2022-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_daycounterblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
