# Generated by Django 3.1.7 on 2022-09-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_course_is_editable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='description',
            new_name='ru_description',
        ),
        migrations.AddField(
            model_name='npc',
            name='en_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npc',
            name='en_tags',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npc',
            name='is_scientific_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='npc',
            name='ru_tags',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='npc',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
    ]
