# Generated by Django 3.1.7 on 2022-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_auto_20220922_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='ru_name',
        ),
        migrations.AddField(
            model_name='location',
            name='en_name',
            field=models.CharField(default='', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='npc',
            name='en_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='ru_description',
            field=models.TextField(blank=True),
        ),
    ]
