# Generated by Django 3.1.7 on 2022-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_auto_20220923_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
