# Generated by Django 3.1.7 on 2022-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_auto_20220926_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberblock',
            name='correct',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='numberblock',
            name='tolerance',
            field=models.FloatField(),
        ),
    ]
