# Generated by Django 3.1.7 on 2022-10-13 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_faculty'),
        ('lessons', '0018_auto_20220930_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBranchingChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_local_id', models.CharField(max_length=120)),
                ('branching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.branching')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMapImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course_map_images')),
                ('image_disabled', models.ImageField(upload_to='course_map_images')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course')),
            ],
        ),
    ]
