# Generated by Django 3.1.7 on 2022-10-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_coursemapimg_profilebranchingchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebranchingchoice',
            name='choose_local_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
