# Generated by Django 3.1.7 on 2022-10-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_auto_20221013_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemapimg',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
