# Generated by Django 3.1.7 on 2022-10-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_question_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='locale',
            field=models.JSONField(default={'en': [], 'ru': []}),
        ),
    ]
