# Generated by Django 3.1.7 on 2022-10-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_profilelessondone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('laboratory_choice', 'Laboratory Choice'), ('job_choice', 'Job Choice')], max_length=31)),
                ('content', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='profile_affect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.unitaffect'),
        ),
        migrations.AddField(
            model_name='unit',
            name='profile_affect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.unitaffect'),
        ),
    ]
