# Generated by Django 3.1.7 on 2022-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_review_mail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaffect',
            name='code',
            field=models.CharField(choices=[('laboratory_choice', 'Laboratory Choice'), ('job_choice', 'Job Choice'), ('salary', 'Salary')], max_length=31),
        ),
    ]
