# Generated by Django 3.1.7 on 2022-11-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_profileavatarbrows_face'),
        ('lessons', '0028_auto_20221028_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilelessondone',
            options={'ordering': ('finished_at',), 'verbose_name': 'ProfileLessonDone', 'verbose_name_plural': 'ProfileLessonsDone'},
        ),
        migrations.CreateModel(
            name='ProfileCourseDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'ProfileCourseDone',
                'verbose_name_plural': 'ProfileCoursesDone',
                'ordering': ('finished_at',),
            },
        ),
    ]
