# Generated by Django 3.1.7 on 2022-11-08 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20221107_2307'),
        ('lessons', '0029_auto_20221102_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelessondone',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_done', to='accounts.profile'),
        ),
    ]
