# Generated by Django 3.1.7 on 2022-11-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0030_auto_20221109_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='locale',
            field=models.JSONField(default={'en': {}, 'ru': {}}),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='locale',
            field=models.JSONField(default={'en': {}, 'ru': {}}),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='markup',
            field=models.JSONField(default={'en': {}, 'ru': {}}),
        ),
    ]
