# Generated by Django 3.1.7 on 2024-04-07 14:33

from django.db import migrations, models
import django.db.models.deletion
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20240407_1733'),
        ('lessons', '0033_auto_20240215_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(default=1)),
                ('npc', models.IntegerField(default=1)),
                ('lesson_name', models.CharField(default='', max_length=32)),
                ('lesson_number', models.IntegerField(default=0)),
                ('quest_number', models.IntegerField(default=0)),
                ('locales', models.JSONField(default=lessons.models.default_locale)),
                ('lesson_id', models.CharField(blank=True, default='', max_length=64)),
                ('skipped', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLessonChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('content', models.JSONField(default={})),
                ('unit_id', models.CharField(blank=True, default='', max_length=64)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk', to='lessons.profilelesson')),
            ],
        ),
    ]
