version: '3'

services:
    lis_db:
        image: postgres
        container_name: lis_db
        expose:
            - 5432
        environment:
            - POSTGRES_USER=maindb
            - POSTGRES_PASSWORD=maindb
            - POSTGRES_DB=maindb
        volumes:
            - postgres_data:/var/lib/postgresql

    redis:
        image: redis:alpine

    backend:
        restart: always
        container_name: lis_back
        build: ./django_core
        env_file:
            environments/app.env
        command: bash -c "
                python3 manage.py makemigrations &&
                python3 manage.py migrate &&
                python manage.py collectstatic --noinput &&
                gunicorn -w 3 django_core.wsgi:application --bind 0.0.0.0:8000 --reload"
        volumes:
            - ./django_core:/django_core
        expose:
            - 8000
        depends_on:
            - lis_db
            - redis
    
    nginx:
        container_name: lis_nginx
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - backend
        volumes:
            - ./django_core/static:/static
            - ./django_core/media:/media
            - ./nginx:/etc/nginx/conf.d
            - ../lis-front/editor/build:/var/www/html/editor

    celery:
        build: ./django_core
        command: celery -A django_core worker -l info
        env_file:
            environments/app.env
        volumes:
            - ./django_core:/django_core
        depends_on:
            - backend

    celery-beat:
        build: ./django_core
        command: celery -A django_core beat -l info
        env_file:
            environments/app.env
        volumes:
            - ./django_core:/django_core
        depends_on:
            - backend
volumes:
    postgres_data: {}
