# Generated by Django 3.1.7 on 2022-10-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220926_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
