# Generated by Django 3.1.7 on 2022-10-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(choices=[('it', ''), ('it', ''), ('it', ''), ('it', ''), ('it', ''), ('it', '')], max_length=120),
        ),
    ]
