# Generated by Django 3.1.7 on 2022-10-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221013_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='faculty',
        ),
        migrations.AddField(
            model_name='profile',
            name='laboratories',
            field=models.CharField(choices=[('it', 'IT'), ('ls', 'Науки о жизни'), ('mi', 'Менеджмент и инновации'), ('ctm', 'Компьютерные технологии и управления'), ('pts', 'Физико-технические науки')], default='it', max_length=120),
        ),
    ]
