# Generated by Django 3.1.7 on 2022-10-13 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221013_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='laboratories',
            new_name='laboratory',
        ),
        migrations.AddField(
            model_name='profile',
            name='university_position',
            field=models.CharField(
                choices=[('Студент', 'Student'), ('Стажер', 'Intern'), ('Лаборант', 'Laboratory Assistant'),
                         ('Инженер', 'Engineer'), ('Мл. научный сотрудник', 'Jun Research Assistant')],
                default='Студент', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
