# Generated by Django 3.1.7 on 2022-10-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221013_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='laboratories',
            new_name='laboratory',
        ),
    ]
