# Generated by Django 3.1.7 on 2022-10-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_coursemapimg_order'),
        ('accounts', '0010_auto_20221014_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dress_form',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='face_form',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='hair_form',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='head_form',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='scientific_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.npc'),
        ),
        # migrations.AddField(
        #     model_name='profile',
        #     name='university_position',
        #     field=models.CharField(choices=[('Студент', 'Student'), ('Стажер', 'Intern'), ('Лаборант', 'Laboratory Assistant'), ('Инженер', 'Engineer'), ('Мл. научный сотрудник', 'Jun Research Assistant')], default='Студент', max_length=40),
        # ),
    ]
