# Generated by Django 3.1.7 on 2022-10-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20221014_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ultimate_activated',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ultimate_finish_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
