# Generated by Django 3.1.7 on 2022-10-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dress_form',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='face_form',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hair_form',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='head_form',
        ),
    ]
