# Generated by Django 3.1.7 on 2022-10-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20221019_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAvatarClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6)),
                ('usual_part', models.ImageField(default='woman_parts/Brows/1 type/Woman-1-clothes-usual@4x.png', upload_to='body_part/clothes/')),
                ('fair_part', models.ImageField(default='woman_parts/Brows/1 type/Woman-1-clothes-fair@4x.png', upload_to='body_part/clothes/')),
                ('happy_part', models.ImageField(default='woman_parts/Brows/1 type/Woman-1-clothes-happy@4x.png', upload_to='body_part/clothes/')),
                ('angry_part', models.ImageField(default='woman_parts/Brows/1 type/Woman-1-clothes-angry@4x.png', upload_to='body_part/clothes/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='cloth_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profileavatarclothes'),
        ),
        migrations.DeleteModel(
            name='ProfileAvatarCloth',
        ),
    ]
