# Generated by Django 3.1.7 on 2022-10-31 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20221028_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileavatarbrows',
            options={'verbose_name': 'ProfileAvatarBrows', 'verbose_name_plural': 'ProfileAvatarBrows'},
        ),
        migrations.AlterModelOptions(
            name='profileavatarclothes',
            options={'verbose_name': 'ProfileAvatarClothes', 'verbose_name_plural': 'ProfileAvatarClothes'},
        ),
        migrations.AlterModelOptions(
            name='profileavatarface',
            options={'verbose_name': 'ProfileAvatarFace', 'verbose_name_plural': 'ProfileAvatarFaces'},
        ),
        migrations.AlterModelOptions(
            name='profileavatarhair',
            options={'verbose_name': 'ProfileAvatarHair', 'verbose_name_plural': 'ProfileAvatarHair'},
        ),
        migrations.AlterModelOptions(
            name='profileavatarhead',
            options={'verbose_name': 'ProfileAvatarHead', 'verbose_name_plural': 'ProfileAvatarHeads'},
        ),
    ]
