# Generated by Django 3.1.7 on 2022-11-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20221101_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileavatarbrows',
            name='face',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brows_list', to='accounts.profileavatarhead'),
        ),
        migrations.AddField(
            model_name='profileavatarhair',
            name='color',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
