# Generated by Django 3.1.7 on 2022-11-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20221102_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatarbrows',
            name='face',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brows_list', to='accounts.profileavatarface'),
        ),
    ]
