# Generated by Django 3.1.7 on 2022-11-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20221102_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileavatarbrows',
            name='color',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
