# Generated by Django 3.1.7 on 2022-11-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profileavatarbrows_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileavatarbrows',
            name='face',
        ),
    ]
