# Generated by Django 3.1.7 on 2022-11-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_profileavatarbrows_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileavatarbrows',
            name='face',
            field=models.ManyToManyField(blank=True, default=None, related_name='brows_list', to='accounts.ProfileAvatarFace'),
        ),
    ]
