# Generated by Django 3.1.7 on 2022-11-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_auto_20221028_1730'),
        ('accounts', '0026_profileavatarbrows_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='lessons.course'),
        ),
    ]
