# Generated by Django 3.1.7 on 2022-11-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_profileavatarbrows_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatarbrows',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
