# Generated by Django 3.1.7 on 2024-02-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_tasks_correct',
            field=models.BooleanField(default=False),
        ),
    ]
