# Generated by Django 3.1.7 on 2022-08-24 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0002_bonuses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonuses',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resources',
            name='energy_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resources',
            name='money_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resources',
            name='time_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resources',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
