# Generated by Django 3.1.7 on 2022-08-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20220824_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='energy_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resources',
            name='money_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resources',
            name='time_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
