# Generated by Django 3.1.7 on 2022-10-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221014_1223'),
        ('resources', '0004_auto_20220824_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotiondata',
            options={'verbose_name': 'EmotionData', 'verbose_name_plural': 'EmotionsData'},
        ),
        migrations.AlterModelOptions(
            name='resources',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterField(
            model_name='emotiondata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='accounts.profile'),
        ),
    ]
