# Generated by Django 3.1.7 on 2022-10-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_review_mail_type'),
        ('resources', '0005_auto_20221014_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotiondata',
            name='emotion_content',
        ),
        migrations.AddField(
            model_name='emotiondata',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotiondata',
            name='emotion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotiondata',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
            preserve_default=False,
        ),
    ]
