# Generated by Django 3.1.7 on 2022-10-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20221026_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotiondata',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='emotiondata',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
