# Generated by Django 3.1.7 on 2024-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20221026_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='can_skip_lesson',
            field=models.BooleanField(default=True),
        ),
    ]
