# Generated by Django 3.1.7 on 2024-02-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='reviewe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='completed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
