# Generated by Django 3.1.7 on 2022-08-17 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_has_bonuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('local_id', models.CharField(blank=True, max_length=255, null=True, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
