# Generated by Django 3.1.7 on 2022-08-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0002_editorsession'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='editorsession',
            constraint=models.UniqueConstraint(fields=('course', 'local_id'), name='only one user to edit'),
        ),
    ]
