# Generated by Django 3.1.7 on 2022-08-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_has_bonuses'),
        ('editors', '0003_auto_20220817_0549'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='editorsession',
            name='only one user to edit',
        ),
        migrations.AlterUniqueTogether(
            name='editorsession',
            unique_together={('course', 'local_id')},
        ),
    ]
