# Generated by Django 3.1.7 on 2022-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0004_auto_20220817_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorsession',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='editorsession',
            unique_together=set(),
        ),
    ]
