name: Deploy

on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 12.x
            - name: Setup
              run: |
                apt-get update
                apt-get install rsync -y
                mkdir "$HOME/.ssh"
                echo "${{ secrets.VPS_PRIVATE_KEY }}" > "$HOME/.ssh/key"
                chmod 600 "$HOME/.ssh/key"
            - name: Delivery
              run: |
                rsync -r * ${{ secrets.VPS_USER_NAME }}@${{ secrets.VPS_SERVER_NAME }}:~/lis-back/
            - name: Building on server
              run: |
                ssh ${{ secrets.VPS_USER_NAME }}@${{ secrets.VPS_SERVER_NAME }} 'cd lis-back && docker-compose up -d --build'
